name: Tests

on:
    push:
        branches:
            - master

env:
    NODE_VERSION: "12.x"

jobs:
    build:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - name: install and test
              run: |
                  npm i
                  CI=true npm run test
